[workspace]
members = [
    "hs-audio-core",
    "hs-core",
    "hs-image-core",
    "hs-mm-embeddings",
    "hs-mm-embeddings-examples",
    "hs-text-core"
]



[package]
name = "handspring"
version = "0.1.0"
edition = "2021"

#[dependencies]

