[package]
name = "hs-audio-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hs-core = { path = "../hs-core" }
candle-core = { workspace = true }
candle-nn = { workspace = true }
serde = { workspace = true }