[package]
name = "hs-mm-embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
hs-image-core = { path = "../hs-image-core" }
hs-text-core = { path = "../hs-text-core" }
hs-audio-core = { path = "../hs-audio-core" }

[features]
default = []