[package]
name = "hs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }
thiserror = "1.0.57"
anyhow = "1.0.79"
